### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by rista404** [philippkuehn/gridilydidily#2]
Hey!

This grid looks awesome, but the problem is it's (a bit) hard to install.
It would be lovely if you could create a package on `npm`, include a minified css version, and maybe put it up on a cdn.

Thanks, keep up the good work!

**Comment by philippkuehn** [comment]
Hi,

You just have to copy the files into your project folder. Then add this to your .scss-file:

```
@import "gridilydidily.scss";
```

If you want to customize some settings you have to copy the `$grid-settings` map before your `@import`.
Maybe I should add these instructions to the demo page.

And I don't want to make a .css-file available because it's a sass project.

**Comment by rista404** [comment]
Yeah I know how to include it in my project, but there are a bunch of ways to do it easier...

It is a sass project, but nonetheless it will be compiled to a css file. Maybe someone wants to use the grid, without including the hole project. It doesn't make sense not to include a minified css file.
