### ISSUE TITLE
Filesize

### ISSUE THREAD

**Issue by tomgreenhill** [philippkuehn/gridilydidily#4]
Hey, 

I've been using gridilydidily on a project and only recently whilst doing some speed tests did I check the size of the outputted CSS. The addition of gridilydidily adds a whopping 103k to the CSS.

Is there any way of getting this down? I'm not pointing the finger, just wondering if perhaps there's anything I can strip back etc.

Cheers,
Tom

**Comment by philippkuehn** [comment]
Hey,

sorry for the late response. In your `$grid-settings` you can disable all of the options and modifiers you don't need. This can save much space! Anyway you should gzip your CSS. Gridilydidily performs very well at gziping because there is much similar code that will be generated so the gziped size is only about 1/10th of the uncompressed size.

Cheers,
Phil

**Comment by tomgreenhill** [comment]
Hey Phil, 

No worries at all. After I wrote this I went and checked out the settings and got it down. Yeah good point, I'm working locally at the moment so was just going by filesize. It will all be gzipped! 

Cheers,
Tom
